document.writeln("		<div id=\'header\' class=\'header2\'>");
document.writeln("            <div class=\'top-header hidden-xs\'>");
document.writeln("");
document.writeln("                <div class=\'container container110\'>");
document.writeln("                    <ul class=\'nav navbar-nav col-sm-4 hidden-xs\'>");
document.writeln("                        <li><a href=\'http://en.sjtu.edu.cn/\' style=\' padding-top: 12px; \' target=\'_blank\'>ENGLISH</a></li>");
document.writeln("                    </ul>");
document.writeln("                    <ul class=\'nav navbar-nav col-sm-8 nav-right no-padding\'>");
document.writeln("                        <li class=\'dropdown119\'>");
document.writeln("                            <a href=\'#\' data-toggle=\'dropdown\'><i class=\'iconfont icon-xueyuanxinxi\'></i> 院系设置</a>");
document.writeln("                            <div class=\'dropdown-menu dropdown-menu1110 clearfix\'>");
document.writeln("                                <div class=\'dropdown-item dropdown-item119\'>");
document.writeln("                                    <h3 class=\'dropdown-item-title\'>工科</h3>");
document.writeln("                                    <ul class=\'dropdown-item-list\'>");
document.writeln("                                        <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://naoce.sjtu.edu.cn\' target=\'_blank\'>船舶海洋与建筑工程学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://me.sjtu.edu.cn\' target=\'_blank\'>机械与动力工程学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.seiee.sjtu.edu.cn\' target=\'_blank\'>电子信息与电气工程学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://smse.sjtu.edu.cn\' target=\'_blank\'>材料科学与工程学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a  class=\'pad-left25\' href=\'http://sese.sjtu.edu.cn\' target=\'_blank\'>环境科学与工程学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://bme.sjtu.edu.cn\' target=\'_blank\'>生物医学工程学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.aero.sjtu.edu.cn\' target=\'_blank\'>航空航天学院</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("                                 <div class=\'dropdown-item dropdown-item119\'>");
document.writeln("                                    <h3 class=\'dropdown-item-title\'>理科</h3>");
document.writeln("                                    <ul class=\'dropdown-item-list\'>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.math.sjtu.edu.cn\' target=\'_blank\'>数学科学学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.physics.sjtu.edu.cn\' target=\'_blank\'>物理与天文学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://scce.sjtu.edu.cn\' target=\'_blank\'>化学化工学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://zhiyuan.sjtu.edu.cn\' target=\'_blank\'>致远学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://ioo.sjtu.edu.cn/\' target=\'_blank\'>海洋学院</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("                                 <div class=\'dropdown-item dropdown-item119\'>");
document.writeln("                                    <h3 class=\'dropdown-item-title\'>生命科学</h3>");
document.writeln("                                    <ul class=\'dropdown-item-list\'>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://life.sjtu.edu.cn\' target=\'_blank\'>生命科学技术学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.agri.sjtu.edu.cn\' target=\'_blank\'>农业与生物学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.shsmu.edu.cn\' target=\'_blank\'>医学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://pharm.sjtu.edu.cn\' target=\'_blank\'>药学院</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("                                 <div class=\'dropdown-item dropdown-item119\'>");
document.writeln("                                    <h3 class=\'dropdown-item-title\'>人文社科</h3>");
document.writeln("                                    <ul class=\'dropdown-item-list\'>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.acem.sjtu.edu.cn\' target=\'_blank\'>安泰经济与管理学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://law.sjtu.edu.cn\' target=\'_blank\'>凯原法学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://sfl.sjtu.edu.cn\' target=\'_blank\'>外国语学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://shss.sjtu.edu.cn\' target=\'_blank\'>人文学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://ma.sjtu.edu.cn/news\' target=\'_blank\'>马克思主义学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.sipa.sjtu.edu.cn\' target=\'_blank\'>国际与公共事务学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://smd.sjtu.edu.cn\' target=\'_blank\'>媒体与传播学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://tiyuxi.sjtu.edu.cn\' target=\'_blank\'>体育系</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.saif.sjtu.edu.cn\' target=\'_blank\'>上海交通大学上海高级金融学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://dschool.sjtu.edu.cn\' target=\'_blank\'>设计学院</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("                                 <div class=\'dropdown-item dropdown-item119\'>");
document.writeln("                                    <h3 class=\'dropdown-item-title\'>国际化办学</h3>");
document.writeln("                                    <ul class=\'dropdown-item-list\'>");
document.writeln("                                       <li class=\'col-md-3\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://umji.sjtu.edu.cn\' target=\'_blank\'>上海交大密西根学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a href=\'http://speit.sjtu.edu.cn\' target=\'_blank\'>上海交大-巴黎高科卓越工程师学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://icci.sjtu.edu.cn\' target=\'_blank\'>上海交大-南加州大学文化创意产业学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://cn.ceibs.edu\' target=\'_blank\'>中欧国际工商学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6 col-sm-6\'>");
document.writeln("                                            <a  class=\'pad-left25\' href=\'http://lcc.sjtu.edu.cn\' target=\'_blank\'>上海交通大学中英国际低碳学院</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("								");
document.writeln("								<div class=\'dropdown-item dropdown-item119\'>");
document.writeln("                                    <h3 class=\'dropdown-item-title\'>研究院</h3>");
document.writeln("									<ul class=\'dropdown-item-list add-drop14\'>");
document.writeln("                                       <li class=\'col-md-6 \'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.cafr.cn/\' target=\'_blank\' tabtarget=\'34\' retargeta=\'157\' toretabtarget=\'156\'>中国金融研究院</a>");
document.writeln("                                            <small>（上海交通大学上海高级金融学院）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6  \'>");
document.writeln("                                            <a class=\'\' href=\'\' tabtarget=\'35\' retargeta=\'158\' toretabtarget=\'157\'>空天技术研究院</a>");
document.writeln("                                            <small>（航空航天学院）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6 \'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.inrd.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'36\' retargeta=\'159\' toretabtarget=\'158\'>新农村发展研究院</a>");
document.writeln("                                            <small>（农业与生物学院）</small>");
document.writeln("                                        </li>");
document.writeln("                                     ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-6 \'>");
document.writeln("                                            <a class=\'\' href=\'http://med-x.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'37\' retargeta=\'160\' toretabtarget=\'159\'>Med-X 研究院</a>");
document.writeln("                                            <small>（生物医学工程学院）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.bio-x.cn\' target=\'_blank\' tabtarget=\'38\' retargeta=\'161\' toretabtarget=\'160\'>Bio-X 研究院</a>");
document.writeln("											<small>（生命科学技术学院）</small>");
document.writeln("                                        </li>");
document.writeln("                                     ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-6 \'>");
document.writeln("                                            <a class=\'\' href=\'http://design.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'39\' retargeta=\'162\' toretabtarget=\'161\'>创新设计研究中心</a>");
document.writeln("                                            <small>（设计学院）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'\' tabtarget=\'40\' retargeta=\'163\' toretabtarget=\'162\'>出版传媒研究院</a>");
document.writeln("                                            <small>（媒体与传播学院）</small>");
document.writeln("                                        </li>");
document.writeln("                                       ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a class=\'\' href=\'http://ciug.sjtu.edu.cn/Web/Home\' target=\'_blank\' tabtarget=\'41\' retargeta=\'164\' toretabtarget=\'163\'>中国城市治理研究院</a>");
document.writeln("                                            <small>（国际与公共事务学院）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.sugli.sjtu.edu.cn/sugli2010/index.html\' target=\'_blank\' tabtarget=\'42\' retargeta=\'165\' toretabtarget=\'164\'>董浩云航运与物流研究院</a>");
document.writeln("											<small>（安泰经济与管理学院）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a href=\'\' tabtarget=\'43\' retargeta=\'166\' toretabtarget=\'165\'>航空发动机研究院</a>");
document.writeln("                                            <small>（机械与动力工程学院）</small>");
document.writeln("                                       </li>");
document.writeln("                                      ");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'\' tabtarget=\'44\' retargeta=\'167\' toretabtarget=\'166\'>燃气轮机研究院</a>");
document.writeln("                                            <small>（机械与动力工程学院）</small>");
document.writeln("                                       </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a href=\'http://www.auto.sjtu.edu.cn/index.html\' target=\'_blank\' tabtarget=\'45\' retargeta=\'168\' toretabtarget=\'167\'>汽车工程研究院</a>");
document.writeln("											<small>（机械与动力工程学院）</small>");
document.writeln("                                        </li>");
document.writeln("                                      ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://energy.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'46\' retargeta=\'169\' toretabtarget=\'168\'>能源研究院</a>");
document.writeln("                                            <small>（机械与动力工程学院）</small>");
document.writeln("                                        </li>");
document.writeln("                                     ");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a href=\'http://ioo.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'47\' retargeta=\'170\' toretabtarget=\'169\'>海洋研究院</a>");
document.writeln("                                            <small>（海洋学院）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a class=\'pad-left25\' class=\'\' href=\'http://gse.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'48\' retargeta=\'171\' toretabtarget=\'170\'>高等教育研究院</a>");
document.writeln("                                        </li>");
document.writeln("                                      ");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a href=\'http://scsb.sjtu.edu.cn/xtswyx/home.do?method=getHomeList\' target=\'_blank\' tabtarget=\'49\' retargeta=\'172\' toretabtarget=\'171\'>系统生物医学研究院</a>");
document.writeln("                                            ");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://iah.sjtu.edu.cn/cn/home/index.asp\' target=\'_blank\' tabtarget=\'50\' retargeta=\'173\' toretabtarget=\'172\'>人文艺术研究院</a>");
document.writeln("                                        </li>");
document.writeln("                                     ");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a class=\'\' href=\'http://aitri.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'51\' retargeta=\'174\' toretabtarget=\'173\'>先进产业技术研究院</a>");
document.writeln("                                            ");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://shcs.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'52\' retargeta=\'175\' toretabtarget=\'174\'>科学史与科学文化研究院</a>");
document.writeln("                                        </li>");
document.writeln("                                     ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a class=\'\' href=\'http://ins.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'53\' retargeta=\'176\' toretabtarget=\'175\'>自然科学研究院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.shsmu.edu.cn/chdi/\' target=\'_blank\' tabtarget=\'54\' retargeta=\'177\' toretabtarget=\'176\'>中国医院发展研究院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a href=\'http://transmed.sjtu.edu.cn\' target=\'_blank\' tabtarget=\'55\' retargeta=\'178\' toretabtarget=\'177\'>转化医学研究院</a>");
document.writeln("                                        </li>");
document.writeln("                                     ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'https://mooc.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'56\' retargeta=\'179\' toretabtarget=\'178\'>慕课研究院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a href=\'http://tdli.sjtu.edu.cn/web/yjxy/5130001.htm\' target=\'_blank\' tabtarget=\'57\' retargeta=\'180\' toretabtarget=\'179\'>李政道研究所</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6 col-xs-6 \'>");
document.writeln("                                            <a  class=\'pad-left25\' href=\'http://ciq.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'58\' retargeta=\'181\' toretabtarget=\'180\'>中国质量发展研究院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6 col-xs-6\'>");
document.writeln("                                            <a href=\'http://ipmsjtu.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'59\' retargeta=\'182\' toretabtarget=\'181\'>个性化医学研究院 </a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("								");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <!--<li><a href=\'/jgsz/index.html\' target=\'_blank\'>机构设置</a></li>-->");
document.writeln("						<li class=\'dropdown119\'>");
document.writeln("                            <a href=\'#\' data-toggle=\'dropdown\'  aria-expanded=\'true\'><i class=\'iconfont icon-icon-test\'></i>机构设置</a>");
document.writeln("                            <div class=\'dropdown-menu dropdown-menu1110 clearfix\'>");
document.writeln("                                 <div class=\'dropdown-item dropdown-item119\'>");
document.writeln("                                    <h3 class=\'dropdown-item-title\'>职能部门</h3>");
document.writeln("                                    <ul class=\'dropdown-item-list add-drop14\'>");
document.writeln("                                       <li class=\'col-md-12\'>");
document.writeln("                                            <a class=\' pad-left25\' href=\'http://dzb.sjtu.edu.cn/\' target=\'_blank\' >党政办公室</a>");
document.writeln("                                            <small>（<a href=\'http://gfb.sjtu.edu.cn \' target=\'_blank\'>改革与发展研究室、</a>安保委办公室、<a href=\'http://lc.sjtu.edu.cn \' target=\'_blank\'>地方合作办公室、</a>信息化推进办公室；信访工作办公室、法律事务室、机要室）</small>");
document.writeln("                                        </li>");

document.writeln("                                       <li class=\'col-md-6 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://jiwei.sjtu.edu.cn/\' target=\'_blank\' >纪委办公室</a>");
document.writeln("                                            <small>（监察处、巡察工作办公室）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a href=\'http://zzb.sjtu.edu.cn/\' target=\'_blank\' >党委组织部</a>");
document.writeln("                                            <small>（党校、机关党委、老干部处）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <br clear=\'all\'> ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-9 \'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.sjtu.edu.cn/xcb/\' target=\'_blank\' >党委宣传部</a>");
document.writeln("                                            <small>（<a href=\'http://news.sjtu.edu.cn \' target=\'_blank\'>新闻中心、</a><a href=\'http://wm.sjtu.edu.cn \' target=\'_blank\'>精神文明办公室</a>；网络宣传与管理领导小组办公室）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-3\'>");
document.writeln("                                            <a href=\'http://tzb.sjtu.edu.cn/\' target=\'_blank\'>党委统战部</a>");
document.writeln("                                        </li>");
document.writeln("                                       <br clear=\'all\'> ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://hr.sjtu.edu.cn/\' target=\'_blank\' >党委教师工作部</a>");
document.writeln("                                            <small>（与人力资源处合署）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a href=\'http://sac.sjtu.edu.cn/\' target=\'_blank\' >学生工作指导委员会</a>");
document.writeln("                                            <small>（学生处、团委、人民武装部）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <br clear=\'all\'> ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://gh.sjtu.edu.cn/web/sjtugh/4710001.htm\' target=\'_blank\' >工会</a>");
document.writeln("                                            <small>（<a href=\'http://fwh.sjtu.edu.cn \' target=\'_blank\'>妇女工作委员会</a>）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3\'>");
document.writeln("                                            <a href=\'http://www.gs.sjtu.edu.cn/\' target=\'_blank\' >研究生院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a href=\'http://www.jwc.sjtu.edu.cn/web/sjtu/198001.htm\' target=\'_blank\' >教务处</a>");
document.writeln("                                            <small>（<a href=\'http://zsb.sjtu.edu.cn \' target=\'_blank\'>招生办公室、</a><a href=\'https://mooc.sjtu.edu.cn \' target=\'_blank\'>慕课(MOOCs)推进办公室</a>）</small>");
document.writeln("                                       </li>");
document.writeln("                                       <br clear=\'all\'> ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-6 col-sm-9\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://kejichu.sjtu.edu.cn/\' target=\'_blank\' >科学技术发展研究院</a>");
document.writeln("                                            <small>（先进技术与装备研究院）</small>");
document.writeln("                                       </li>");
document.writeln("                                       <li class=\'col-md-3\'>");
document.writeln("                                            <a href=\'http://wk.sjtu.edu.cn/\' target=\'_blank\' >文科建设处</a>");
document.writeln("                                        </li>");
document.writeln("                                       <br clear=\'all\'> ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-8 col-xs-12\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://global.sjtu.edu.cn/\' target=\'_blank\' >国际合作与交流处</a>");
document.writeln("                                            <small>（<a href=\'http://global.sjtu.edu.cn/hmt\' target=\'_blank\'>港澳台办公室</a>；<a href=\'http://cgcj.sjtu.edu.cn \' target=\'_blank\'>出入境管理与服务中心、</a><a href=\'http://isc.sjtu.edu.cn \' target=\'_blank\'>留学生发展中心</a>）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <br clear=\'all\'> ");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://hr.sjtu.edu.cn/\' target=\'_blank\' >人力资源处</a>");
document.writeln("                                            <small>（人才引进与服务中心；退休人员事务中心）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-3 \'>");
document.writeln("                                            <a class=\'\' href=\'http://www.jdcw.sjtu.edu.cn/\' target=\'_blank\' >财务计划处</a>");
document.writeln("                                        </li>");
document.writeln("                                       <br clear=\'all\'> ");
document.writeln("                                       <li class=\'col-md-6 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'https://plan.sjtu.edu.cn/\' target=\'_blank\' >规划发展处</a>");
document.writeln("                                            <small>（<a href=\'https://985.sjtu.edu.cn \' target=\'_blank\'>重点建设办公室</a>）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-3\'>");
document.writeln("                                            <a href=\'http://sjchu.sjtu.edu.cn/\' target=\'_blank\' >审计处</a>");
document.writeln("                                        </li>");
document.writeln("                                       <br clear=\'all\'> ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'\' target=\'_blank\' >信息安全管理办公室</a>");
document.writeln("                                            <small>（科研生产质量管理办公室）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://zcc.sjtu.edu.cn/\' target=\'_blank\' >资产管理与实验室处</a>");
document.writeln("                                        </li>");
document.writeln("                                       <br clear=\'all\'> ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-6 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://jzb.sjtu.edu.cn/\' target=\'_blank\' >国有资产监督管理委员会办公室  </a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-3\'>");
document.writeln("                                            <a href=\'http://bwc.sjtu.edu.cn/\' target=\'_blank\' >保卫处</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-3\'>");
document.writeln("                                            <a href=\'https://jjc.sjtu.edu.cn/\' target=\'_blank\' >基建处</a>");
document.writeln("                                        </li>");
document.writeln("                                       <br clear=\'all\'> ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-3 col-sm-3\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://foundation.sjtu.edu.cn/site/index.php\' target=\'_blank\' >发展联络处</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://alumni.sjtu.edu.cn/newalu/\' target=\'_blank\' >校友总会办公室</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a  href=\'http://zbb.sjtu.edu.cn/\' target=\'_blank\' >招投标与政府采购办公室</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://xygl.sjtu.edu.cn/\' target=\'_blank\' >校园管理办公室 </a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("                                 <div class=\'dropdown-item dropdown-item119\'>");
document.writeln("                                    <h3 class=\'dropdown-item-title\'>直属单位</h3>");
document.writeln("                                    <ul class=\'dropdown-item-list add-drop1402\'>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.lib.sjtu.edu.cn/\' target=\'_blank\'>图书馆</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://archives.sjtu.edu.cn/\' target=\'_blank\' >档案馆</a><small>（党史校史研究室）</small>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://etc.sjtu.edu.cn/\' target=\'_blank\' >教育技术中心</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a  href=\'https://net.sjtu.edu.cn/\' target=\'_blank\' >网络信息中心</a>");
document.writeln("                                        </li>");
document.writeln("                                       <br clear=\'all\'> ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://iac.sjtu.edu.cn/\' target=\'_blank\' >分析测试中心</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.si.sjtu.edu.cn/\' target=\'_blank\' >学生创新中心</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://ctld.sjtu.edu.cn/\' target=\'_blank\'>教学发展中心</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a  href=\'http://sce.sjtu.edu.cn/\' target=\'_blank\' >继续教育学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <br clear=\'all\'> ");
document.writeln("");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.qianxslib.sjtu.edu.cn/\' target=\'_blank\' >钱学森图书馆</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://houqin.sjtu.edu.cn/\' target=\'_blank\'>后勤保障中心</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.oec.sjtu.edu.cn/\' target=\'_blank\'>海外教育学院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://chuangye.sjtu.edu.cn/\' target=\'_blank\' >创业学院</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("                                 <div class=\'dropdown-item dropdown-item119\'>");
document.writeln("                                    <h3 class=\'dropdown-item-title\'>直属企业</h3>");
document.writeln("                                    <ul class=\'dropdown-item-list\'>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://tzjt.sjtu.edu.cn/web/jdcy/3680001.htm\' target=\'_blank\' >上海交大产业投资管理（集团）有限公司</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3\'>");
document.writeln("                                            <a href=\'https://www.sjtu.edu.cn\' target=\'_blank\' >上海交大企业管理中心</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://ipm.sjtu.edu.cn/\' target=\'_blank\' >上海交大知识产权管理有限公司</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a href=\'http://jfjt.sjtu.edu.cn/\' target=\'_blank\'>上海交大教育服务产业投资管理（集团）有限公司</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.jiaodapress.com.cn/\'>上海交通大学出版社有限公司 </a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-6\'>");
document.writeln("                                            <a href=\'http://cuti.sjtu.edu.cn/\' target=\'_blank\' >上海交大海洋水下工程科学研究院有限公司</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("                                 <div class=\'dropdown-item dropdown-item119\'>");
document.writeln("                                    <h3 class=\'dropdown-item-title\'>附属医院</h3>");
document.writeln("                                    <ul class=\'dropdown-item-list\'>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.rjh.com.cn/2013ruijin/ruijin/sy/index.shtml\' target=\'_blank\' >瑞金医院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'https://www.renji.com/\' target=\'_blank\' >仁济医院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.xinhuamed.com.cn/\' target=\'_blank\' tabtarget=\'79\' toretabtarget=\'174\' retargeta=\'175\'>新华医院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.9hospital.com.cn/\' target=\'_blank\' tabtarget=\'80\' toretabtarget=\'175\' retargeta=\'176\'>第九人民医院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.firsthospital.cn/home/index.html\' target=\'_blank\' tabtarget=\'81\' toretabtarget=\'176\' retargeta=\'177\'>上海市第一人民医院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.6thhosp.com/\' target=\'_blank\' tabtarget=\'82\' toretabtarget=\'177\' retargeta=\'178\'>上海市第六人民医院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.scmc.com.cn/root/ProtalPage/List/index.htm\' target=\'_blank\' tabtarget=\'83\' toretabtarget=\'178\' retargeta=\'179\'>上海儿童医学中心</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.shchildren.com.cn/\' target=\'_blank\' tabtarget=\'84\' toretabtarget=\'179\' retargeta=\'180\'>上海市儿童医院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.shxkyy.com/\' target=\'_blank\' tabtarget=\'85\' toretabtarget=\'180\' retargeta=\'181\'>上海市胸科医院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.smhc.org.cn/\' target=\'_blank\' tabtarget=\'86\' toretabtarget=\'181\' retargeta=\'182\'>上海市精神卫生中心</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'https://www.ipmch.com.cn/\' target=\'_blank\' tabtarget=\'87\' toretabtarget=\'182\' retargeta=\'183\'>国际和平妇幼保健院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.cnchospital.com/\' target=\'_blank\' tabtarget=\'88\' toretabtarget=\'183\' retargeta=\'184\'>同仁医院</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.kowloonhospital.com/\' target=\'_blank\' tabtarget=\'89\' toretabtarget=\'184\' retargeta=\'185\'>苏州九龙医院</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("                                 <div class=\'dropdown-item dropdown-item119\'>");
document.writeln("                                    <h3 class=\'dropdown-item-title\'>附属学校</h3>");
document.writeln("                                    <ul class=\'dropdown-item-list\'>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'http://www.jdfz.sh.cn/\' target=\'_blank\' tabtarget=\'90\' toretabtarget=\'185\' retargeta=\'186\'>上海交通大学附属中学</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://www.jd2fz.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'91\' toretabtarget=\'186\' retargeta=\'187\'>上海交通大学第二附属中学</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://jdfx.xhedu.sh.cn/\' target=\'_blank\' tabtarget=\'92\' toretabtarget=\'187\' retargeta=\'188\'>上海交通大学附属小学</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'http://jdfx.mhedu.sh.cn/\' target=\'_blank\' tabtarget=\'93\' toretabtarget=\'188\' retargeta=\'189\'>上海交通大学附属实验小学</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a class=\'pad-left25\' href=\'https://www.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'94\' toretabtarget=\'189\' retargeta=\'190\'>上海交通大学幼儿园</a>");
document.writeln("                                        </li>");
document.writeln("                                       <li class=\'col-md-3 col-sm-6\'>");
document.writeln("                                            <a href=\'https://www.sjtu.edu.cn/\' target=\'_blank\' tabtarget=\'95\' toretabtarget=\'190\' retargeta=\'191\'>上海交通大学闵行幼儿园</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'\'><a href=\'#\' class=\'search\' > <i class=\'iconfont icon-sousuo1\'></i>交大搜索");
document.writeln("                        </a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <div class=\'container\'>");
document.writeln("");
document.writeln("                <div class=\'navbar hidden-xs\'>");
document.writeln("");
document.writeln("                    <div class=\'collapse navbar-collapse no-padding\' id=\'mainNav\'>");
document.writeln("");
document.writeln("						<form class=\'navbar-form\' action=\'https://search.sjtu.edu.cn/search-all/search/data\' method=\'GET\' target=\'_blank\' class=\'form-search\'>");
document.writeln("                            <div class=\'form-group\'>");
document.writeln("                                <input class=\'form-control\' type=\'text\' id=\'keyword\' name=\'keyword\' placeholder=\'请输入关键字搜索上海交大所有网站内容...\'>");
document.writeln("                                <div class=\'addOn\'>");
document.writeln("                                    <button role=\'button\' type=\'submit\'>");
document.writeln("                                        <i class=\'iconfont icon-sousuo1\'></i>");
document.writeln("                                    </button>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </form>");
document.writeln("");
document.writeln("                        <div class=\'navbar-header\'>");
document.writeln("                            <h1 class=\'logo hidden-xs\'>");
document.writeln("                                <a class=\'navbar-brand\' href=\'https://www.sjtu.edu.cn/\'>");
document.writeln("                                    <img src=\'https://www.sjtu.edu.cn/resource/assets/img/LogoWhite.png\'>");
document.writeln("                                </a>");
document.writeln("                            </h1>");
document.writeln("                        </div>");
document.writeln("");
document.writeln("                        <div class=\'navbar-top\'>");
document.writeln("                            <ul class=\'nav navbar-nav\'>");
document.writeln("                                <li><a href=\'https://www.sjtu.edu.cn/fk/index.html\' target=\'_blank\'><i class=\'iconfont icon-yonghu2\'></i> 访客</a></li>");
document.writeln("                                <li><a href=\'https://www.sjtu.edu.cn/xs/index.html\' target=\'_blank\'><i class=\'iconfont icon-xuesheng1\'></i> 学生</a></li>");
document.writeln("                                <li><a href=\'https://www.sjtu.edu.cn/js/index.html\' target=\'_blank\'><i class=\'iconfont icon-laoshicopy\'></i> 教师</a></li>");
document.writeln("                                <li><a href=\'https://www.sjtu.edu.cn/xy/index.html\' target=\'_blank\'><i class=\'iconfont icon-yonghuguanli\'></i> 校友</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("");
document.writeln("                <div class=\'navbar navbar-default navbar-main stickUp-Nav\' role=\'navigation\'>");
document.writeln("                    <div class=\'visible-xs-block\'>");
document.writeln("                        <a class=\'navbar-brand\' href=\'#\' title=\'手机下显示的LOGO\'>");
document.writeln("                            <img src=\'https://www.sjtu.edu.cn/resource/assets/img/LogoWhite.png\'>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                    <div id=\'mobile-navigation\' class=\'phone-nav1220\'>");
document.writeln("");
document.writeln("                        <div class=\'logo1220 pc-hide1220\'> <img src=\'https://www.sjtu.edu.cn/resource/assets/img/LogoWhite.png\'></div>");
document.writeln("                        <ul class=\'nav1220 clearfix pc-hide1220\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'##\'><i class=\'iconfont icon-duoyuyan\'></i>ENGLISH</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'##\'><i class=\'iconfont icon-sousuo1\'></i>交大搜索</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'https://www.sjtu.edu.cn/yxsz/\'><i class=\'iconfont icon-xueyuanxinxi\'></i>院系设置</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'https://www.sjtu.edu.cn/jgsz/\'><i class=\'iconfont icon-icon-test\'></i>机构设置</a>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("");
document.writeln("");
document.writeln("                        <ul class=\'nav navbar-nav middle-nav1220  clearfix\'>");
document.writeln("                            <li class=\'dropdown\'>");
document.writeln("                                <a href=\'#\' data-toggle=\'dropdown\'>关于交大</a>");
document.writeln("                                <div class=\'dropdown-menu dropdown-menu01 clearfix\'>");
document.writeln("                                    <div class=\'dropdown-item clearfix\'>");
document.writeln("                                        <ul class=\'dropdown-item-list\'>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'https://www.sjtu.edu.cn/xxjj/index.html\' target=\'_blank\'>学校简介</a></li>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'https://www.sjtu.edu.cn/lsyg/index.html\' target=\'_blank\'>历史沿革</a></li>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'https://www.sjtu.edu.cn/jdld/index.html\' target=\'_blank\'>交大领导</a></li>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'https://www.sjtu.edu.cn/lrld/index.html\' target=\'_blank\'>历任领导</a></li>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'https://www.sjtu.edu.cn/jdnb/index.html\' target=\'_blank\'>交大年报</a></li>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'https://www.sjtu.edu.cn/sjtj/index.html\' target=\'_blank\'>数据统计</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'dropdown\'>");
document.writeln("                                <a href=\'#\' data-toggle=\'dropdown\'>人才培养</a>");
document.writeln("");
document.writeln("                                <div class=\'dropdown-menu dropdown-menu02 ColThree clearfix\'>");
document.writeln("                                    <div class=\'dropdown-item clearfix\'>");
document.writeln("                                        <ul class=\'dropdown-item-list flex-box\'>");
document.writeln("                                            <div class=\'col-sm-6\'>");
document.writeln("                                                <li><a href=\'http://www.jwc.sjtu.edu.cn\' target=\'_blank\'>本科生培养</a></li>");
document.writeln("                                                <li><a href=\'http://electsys.sjtu.edu.cn\' target=\'_blank\'>本科生选课</a></li>");
document.writeln("                                                <li><a href=\'http://zsb.sjtu.edu.cn\' target=\'_blank\'>本科生招生</a></li>");
document.writeln("                                                <li><a href=\'http://ks.sjtu.edu.cn\' target=\'_blank\'>等级考试</a></li>");
document.writeln("                                                <li><a href=\'http://uitp.sjtu.edu.cn\' target=\'_blank\'>创新实践</a></li>");
document.writeln("                                            </div>");
document.writeln("                                            <div class=\'col-sm-6\'>");
document.writeln("                                                <li><a href=\'http://www.gs.sjtu.edu.cn/\' target=\'_blank\'>研究生培养</a></li>");
document.writeln("                                                <li><a href=\'http://www.yjs.sjtu.edu.cn/ssfw/login.jsp\' target=\'_blank\'>研究生选课</a></li>");
document.writeln("                                                <li><a href=\'http://yzb.sjtu.edu.cn/\' target=\'_blank\'>研究生招生</a></li>");
document.writeln("                                                <li><a href=\'http://yzb.sjtu.edu.cn/zsjz.htm\' target=\'_blank\'>招生简章</a></li>");
document.writeln("                                                <li><a href=\'http://www.gs.sjtu.edu.cn/index/yjsjyfwzx.htm\' target=\'_blank\'>综合服务</a></li>");
document.writeln("                                            </div>");
document.writeln("                                            <div class=\'col-sm-6\'>");
document.writeln("                                                <li><a href=\'http://www.job.sjtu.edu.cn/\' target=\'_blank\'>学生就业</a></li>");
document.writeln("                                                <li><a href=\'http://studyabroad.sjtu.edu.cn/\' target=\'_blank\'>海外访学</a></li>");
document.writeln("                                                <li><a href=\'http://sjtu.fanya.chaoxing.com/portal\' target=\'_blank\'>通识MOOC</a></li>");
document.writeln("                                                <li><a href=\'http://engtc.sjtu.edu.cn/\' target=\'_blank\'>学生创新</a></li>");
document.writeln("                                                <li><a href=\'https://www.sjtu.edu.cn/syjxsfzx/index.html\' target=\'_blank\'>实验教学示范中心</a></li>");
document.writeln("                                            </div>");
document.writeln("                                            <div class=\'col-sm-6\'>");
document.writeln("                                                <li><a href=\'http://electsys.sjtu.edu.cn/\' target=\'_blank\'>教学信息服务网</a></li>");
document.writeln("                                                <li><a href=\'http://pingjiao.sjtu.edu.cn/\' target=\'_blank\'>评教与调查统计</a></li>");
document.writeln("                                                <li><a href=\'http://ctld.sjtu.edu.cn/\' target=\'_blank\'>教学发展</a></li>");
document.writeln("                                                <li><a href=\'http://etc.sjtu.edu.cn/\' target=\'_blank\'>教育技术</a></li>");
document.writeln("                                                <li><a href=\'http://fxl.sjtu.edu.cn/\' target=\'_blank\'>非学历教育</a></li>");
document.writeln("                                            </div>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("");
document.writeln("                            </li>");
document.writeln("                            <li class=\' dropdown\'>");
document.writeln("                                <a href=\'#\' data-toggle=\'dropdown\'>师资建设</a>");
document.writeln("                                <div class=\'dropdown-menu dropdown-menu03  clearfix\'>");
document.writeln("                                    <div class=\'dropdown-item clearfix\'>");
document.writeln("                                        <ul class=\'dropdown-item-list\'>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'https://www.sjtu.edu.cn/zgkxyys/index.html\' target=\'_blank\'>两院院士</a></li>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'https://www.sjtu.edu.cn/jcrc/index.html\' target=\'_blank\'>杰出人才</a></li>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'http://rsc2.sjtu.edu.cn/HR/UI/SystemDefault.aspx\' target=\'_blank\'>人事管理</a></li>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'http://join.sjtu.edu.cn/\' target=\'_blank\'>人才招聘</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'dropdown\'>");
document.writeln("                                <a href=\'#\'>科学研究</a>");
document.writeln("                                <div class=\'dropdown-menu dropdown-menu04 ColThree clearfix\'>");
document.writeln("                                    <div class=\'dropdown-item clearfix\'>");
document.writeln("                                        <ul class=\'dropdown-item-list flex-box\'>");
document.writeln("                                            <div class=\'col-sm-6\'>");
document.writeln("                                                <li><a href=\'https://www.sjtu.edu.cn/yjy/index.html\' target=\'_blank\'>研究院</a></li>");
document.writeln("                                                <li><a href=\'https://www.sjtu.edu.cn/gjjkypt/index.html\' target=\'_blank\'>国家级科研平台</a></li>");
document.writeln("                                                <li><a href=\'https://www.sjtu.edu.cn/zkjg/index.html\' target=\'_blank\'>智库机构</a></li>");
document.writeln("                                            </div>");
document.writeln("                                            <div class=\'col-sm-6\'>");
document.writeln("                                                <li><a href=\'http://ky.sjtu.edu.cn/epstar/login/index.jsp\' target=\'_blank\'>科研管理系统</a></li>");
document.writeln("                                                <li><a href=\'https://www.sjtu.edu.cn/sbjkypt/index.html\' target=\'_blank\'>省部级科研平台</a></li>");
document.writeln("                                                <li><a href=\'https://www.sjtu.edu.cn/shjdxb/index.html\' target=\'_blank\'>上海交大学报</a></li>");
document.writeln("                                            </div>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'dropdown dropdown-right\'>");
document.writeln("                                <a href=\'#\' data-toggle=\'dropdown\'>全球交大</a>");
document.writeln("                                <div class=\'dropdown-menu dropdown-menu05  clearfix\'>");
document.writeln("                                    <div class=\'dropdown-item clearfix\'>");
document.writeln("                                        <ul class=\'dropdown-item-list\'>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'http://global.sjtu.edu.cn/NewsCenter/NewsList?type=1\' target=\'_blank\'>交流动态</a></li>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'http://isc.sjtu.edu.cn/\' target=\'_blank\'>留学交大</a></li>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'http://studyabroad.sjtu.edu.cn/\' target=\'_blank\'>海外访学</a></li>");
document.writeln("");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'http://global.sjtu.edu.cn/hmt\' target=\'_blank\'>港澳台交流</a></li>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'http://global.sjtu.edu.cn/ci/\' target=\'_blank\'>孔子学院</a></li>");
document.writeln("                                            <li class=\'col-sm-6\'><a href=\'http://cgcj.sjtu.edu.cn/\' target=\'_blank\'>出入境管理</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'dropdown dropdown-right\'>");
document.writeln("                                <a href=\'#\' data-toggle=\'dropdown\'>大学文化</a>");
document.writeln("                                <div class=\'dropdown-menu dropdown-menu06 ColThree clearfix\'>");
document.writeln("                                    <div class=\'dropdown-item clearfix\'>");
document.writeln("                                        <ul class=\'dropdown-item-list flex-box\'>");
document.writeln("                                            <div class=\'col-sm-6\'>");
document.writeln("                                              <li><a href=\'http://wm.sjtu.edu.cn/\' target=\'_blank\'>文明在线</a></li>");
document.writeln("												<li><a href=\'http://wm.sjtu.edu.cn/index.php/index/art/index.html\' target=\'_blank\'>菁菁有戏</a></li>");
document.writeln("												<li><a href=\'http://museum.sjtu.edu.cn/\' target=\'_blank\'>校史馆</a></li>");
document.writeln("												<li><a href=\'http://www.jiaodapress.com.cn/\' target=\'_blank\'>交大出版社</a></li>");
document.writeln("												<li><a href=\'http://vi.sjtu.edu.cn/\' target=\'_blank\'>视觉形象识别系统</a></li>");
document.writeln("                                            </div>");
document.writeln("                                            <div class=\'col-sm-6\'>");
document.writeln("                                              <li><a href=\'http://www.lib.sjtu.edu.cn/\' target=\'_blank\'>图书馆</a></li>");
document.writeln("												<li><a href=\'http://tdlee.sjtu.edu.cn/\' target=\'_blank\'>李政道图书馆</a></li>");
document.writeln("												<li><a href=\'http://www.maritimemuseum.sjtu.edu.cn/\' target=\'_blank\'>董浩云航运博物馆</a></li>");
document.writeln("												<li><a href=\'http://www.qianxslib.sjtu.edu.cn/\' target=\'_blank\'>钱学森图书馆</a></li>");
document.writeln("");
document.writeln("                                            </div>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                        <ul class=\'nav1220 clearfix pc-hide1220\'>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'https://www.sjtu.edu.cn/fk/index.html\' target=\'_blank\'><i class=\'iconfont icon-yonghu2\'></i>访客</a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'https://www.sjtu.edu.cn/xs/index.html\' target=\'_blank\'><i class=\'iconfont icon-xuesheng1\'></i>学生</a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'https://www.sjtu.edu.cn/js/index.html\' target=\'_blank\'><i class=\'iconfont icon-laoshicopy\'></i>教师</a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'https://www.sjtu.edu.cn/xy/index.html\' target=\'_blank\'><i class=\'iconfont icon-yonghuguanli\'></i> 校友</a>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("");
document.writeln("                        <div class=\'navbar-top nav-hide1130\'>");
document.writeln("                            <ul class=\'nav navbar-nav nav1220\'>");
document.writeln("                                <li><a href=\'https://www.sjtu.edu.cn/fk/index.html\' target=\'_blank\'><i class=\'iconfont icon-yonghu2\'></i> 访客</a></li>");
document.writeln("                                <li><a href=\'https://www.sjtu.edu.cn/xs/index.html\' target=\'_blank\'><i class=\'iconfont icon-xuesheng1\'></i> 学生</a></li>");
document.writeln("                                <li><a href=\'https://www.sjtu.edu.cn/js/index.html\' target=\'_blank\'><i class=\'iconfont icon-laoshicopy\'></i> 教师</a></li>");
document.writeln("                                <li><a href=\'https://www.sjtu.edu.cn/xy/index.html\' target=\'_blank\'><i class=\'iconfont icon-yonghuguanli\'></i> 校友</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("");